PUMP_THRESHOLD_15M = 0.12
VOLUME_RATIO_THRESHOLD = 3.0
RSI_THRESHOLD = 85
VWAP_DISTANCE_THRESHOLD = 0.05

RISK_PER_TRADE = 0.005
MAX_OPEN_TRADES = 3
MAX_HOLD_MINUTES = 10
DATABASE_URL = "sqlite:///trades.db"
